name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore WorkflowEngine/WorkflowEngine.sln

    - name: Build
      run: dotnet build WorkflowEngine/WorkflowEngine.sln --configuration ${{ matrix.configuration }} --no-restore

    - name: Execute unit tests
      run: dotnet test WorkflowEngine/tests/WorkflowEngine.Tests/ --configuration ${{ matrix.configuration }} --no-build
